<?php

$lang_var = array();

$lang_var["geral_title"] = "Atlas do Desenvolvimento Humano no Brasil 2013";

$lang_var["lang_id"] = "pt";

$lang_var["menu_home"] = "HOME";
$lang_var["menu_oAtlas"] = "O ATLAS";
$lang_var["menu_destaques"] = "DESTAQUES";
$lang_var["menu_perfil"] = "PERFIL";
$lang_var["menu_consulta"] = "CONSULTA";
$lang_var["menu_arvore"] = "ÁRVORE";
$lang_var["menu_graficos"] = "GRÁFICOS";
$lang_var["menu_ranking"] = "RANKING";
$lang_var["menu_download"] = "DOWNLOAD";
    
$lang_var["home_titlePerfil"] = "Perfil Municipal";
$lang_var["home_titlePerfilRM"] = "Perfil RMs";
$lang_var["home_textoPerfil"] = "Consulte o perfil de seu município";
$lang_var["home_exemploBusca"] = "Digite o nome do município. Ex.: Pouso Alegre, Juruti, Lajeado, etc.";
$lang_var["home_erroBusca"] = "*Selecione um município para continuar";
$lang_var["home_buttonBusca"] = "Busca";
$lang_var["home_titleConsulta"] = "Consulta";
$lang_var["home_textoConsulta"] = "Crie seus próprios mapas e gráficos. É fácil e rápido."; 
$lang_var["home_buttonPesquisa"] = "Pesquise";
$lang_var["home_titleidhmArvore"] = "IDHM Árvore";
$lang_var["home_textoidhmArvore"] = "Explore a representação gráfica do IDHM";
$lang_var["home_titleDownload"] = "Download";
$lang_var["home_textoDownload"] = "Baixe os dados do Atlas Brasil 2013";
$lang_var["home_banner0"] = "VÍDEO: Você sabe o que é desenvolvimento humano?";
$lang_var["home_banner1"] = "Municípios e faixas de desenvolvimento humano";
$lang_var["home_banner2"] = "IDHM Longevidade, Educação e Renda";
$lang_var["home_title"] = "Início";
$lang_var["home_metaTitle"] = "Atlas do Desenvolvimento Humano no Brasil 2013";
$lang_var["home_metaDescricao"] = "O Atlas do Desenvolvimento Humano no Brasil 2013 é um banco de dados eletrônico feito com o objetivo de democratizar o acesso e aumentar a capacidade de análise sobre informações socioeconômicas relevantes dos municípios brasileiros e das Unidades da Federação. Baseado nos microdados dos censos de 1991 e de 2000 do IBGE (Fundação Instituto Brasileiro de Geografia e Estatística), este sistema disponibiliza informações sobre o Índice de Desenvolvimento Humano Municipal (IDH-M) e 124 outros indicadores georreferenciados de população, educação, habitação, longevidade, renda, desigualdade social e características físicas do território. Com uma navegação simples e auto-explicável, o Atlas permite ao usuário criar seus próprios instrumentos de análise sobre diversas dimensões do desenvolvimento humano, através de mapas temáticos, tabelas, gráficos, relatórios, ordenamento (rankings) de municípios e estados, e ferramentas estatísticas. Os resultados podem ser impressos ou exportados para serem trabalhados em outros programas, como planilhas eletrônicas, por exemplo.";


$lang_var["destaques_title"] = 'DESTAQUES';
$lang_var["destaques_metodologia"] = 'METODOLOGIA';
$lang_var["destaques_faixas_idhm"] = 'FAIXAS IDHM';
$lang_var["destaques_idhmBrasil"] = 'IDHM BRASIL';
$lang_var["destaques_educacao"] = 'EDUCAÇÃO';
$lang_var["destaques_longevidade"] = 'LONGEVIDADE';
$lang_var["destaques_renda"] = 'RENDA';
$lang_var["destaques_titleAba"] = 'Destaques';
$lang_var["destaques_Title"] = 'DESTAQUES';
$lang_var["destaques_metaDescricao"] = 'O Atlas do Desenvolvimento Humano no Brasil 2013 é uma plataforma de consulta ao Índice de Desenvolvimento Humano Municipal – IDHM - de 5.565 municípios brasileiros, além de mais de 180 indicadores de população, educação, habitação, saúde, trabalho, renda e vulnerabilidade, com dados extraídos dos Censos Demográficos de 1991, 2000 e 2010.';
$lang_var["destaques_titleAbaMetodologia"] = 'Destaques - Metodologia';
$lang_var["destaques_metaTitleMet"] = 'DESTAQUES - METODOLOGIA';
$lang_var["destaques_metaDescricaoMet"] = 'Verifique como está o Índice do Desenvolvimento Humano hoje e como é o seu processo de construção.';
$lang_var["destaques_titleAbaFaixasIDHM"] = 'Destaques - Faixas IDHM';
$lang_var["destaques_metaTitleFaixasIDHM"] = 'DESTAQUES - FAIXAS IDHM';
$lang_var["destaques_metaDescricaoFaixasIDHM"] = 'Verifique a evolução do Índice do Desenvolvimento Humano nos municípios brasileiros.';
$lang_var["destaques_titleAbaIDHMBrasil"] = 'Destaques - IDHM Brasil';
$lang_var["destaques_metaTitleIDHMBrasil"] = 'DESTAQUES - IDHM BRASIL';
$lang_var["destaques_metaDescricaoIDHMBrasil"] = 'O Índice de Desenvolvimento Humano Municipal compreende indicadores de três dimensões do desenvolvimento humano: longevidade, educação e renda. O índice varia de 0 a 1. Quanto mais próximo de 1, maior o desenvolvimento humano.';
$lang_var["destaques_titleAbaEducacao"] = 'Destaques - Educação';
$lang_var["destaques_metaTitleEducacao"] = 'DESTAQUES - EDUCAÇÃO';
$lang_var["destaques_metaDescricaoEducacao"] = 'No Índice de Desenvolvimento Humano Municipal – componente Educação – a dimensão “acesso a conhecimento” é medida pela composição de dois subíndices: a escolaridade da população adulta e o fluxo escolar da população jovem.';
$lang_var["destaques_titleAbaLongRenda"] = 'Destaques - Longevidade e Renda';
$lang_var["destaques_metaTitleLongRenda"] = 'DESTAQUES - LONGEVIDADE E RENDA';
$lang_var["destaques_metaDescricaoLongRenda"] = 'El índice de desarrollo humano se compone del indicador Municipal Longevidad de la esperanza de vida al nacer...';

$lang_var["atlas_Metodologia"] = "Metodologia do IDHM 2013";
$lang_var["atlas_titleOAtlas"] = "O Atlas";
$lang_var["atlas_menuOAtlas"] = "O ATLAS";
$lang_var["atlas_menuQuemFaz"] = "QUEM FAZ";
$lang_var["atlas_menuParaQue"] = "PARA QUE";
$lang_var["atlas_menuProcesso"] = "PROCESSO";
$lang_var["atlas_menuDesenvolvimentoHumano"] = "DESENVOLVIMENTO HUMANO";
$lang_var["atlas_menuIdhm"] = "IDHM";
$lang_var["atlas_menuMetodologia"] = "METODOLOGIA";
$lang_var["atlas_menuIdhmLongevidade"] = "IDHM LONGEVIDADE";
$lang_var["atlas_menuIdhmEducacao"] = "IDHM EDUCAÇÃO";
$lang_var["atlas_menuIdhmRenda"] = "IDHM RENDA";
$lang_var["atlas_menuGlossario"] = "GLOSSÁRIO";
$lang_var["atlas_menuFAQ"] = "PERGUNTAS FREQUENTES";
$lang_var["atlas_menututorial"] = "TUTORIAL";
$lang_var["atlas_title"] = "O Atlas";
$lang_var["atlas_metaTitle"] = "Sobre o Atlas";
$lang_var["atlas_metaDescricao"] = "O conceito de desenvolvimento humano nasceu definido como um processo de ampliação das escolhas das pessoas para que elas tenham capacidades e oportunidades para serem aquilo que desejam ser.";
$lang_var["atlas_titleDH"] = "Desenvolvimento humano e IDH";
$lang_var["atlas_metaTitleDH"] = "Desenvolvimento humano e IDH";
$lang_var["atlas_metaDescricaoDH"] = "Desenvolvimento humano é o processo de ampliação das liberdades das pessoas - no que tange suas capacidades e as oportunidades a seu dispor - para que elas possam escolher a vida que desejam viver.";
$lang_var["atlas_titleidhm"] = "O IDHM";
$lang_var["atlas_metaTitleidhm"] = "O IDHM";
$lang_var["atlas_metaDescricaoidhm"] = "Em 2013, o PNUD Brasil, o IPEA e a Fundação João Pinheiro assumiram o desafio de adaptar a metodologia do IDH global para calcular o IDH Municipal (IDHM) de 5.565 municípios brasileiros a partir de dados do Censo Demográfico de 2010. Também recalculou-se o IDHM, a partir da metodologia adotada, para os anos de 1991 e 2000, por meio de uma minuciosa compatibilização das áreas municipais para levar em conta as divisões administrativas ocorridas no período e  permitir a comparabilidade temporal e espacial entre os municípios. O desafio já havia sido enfrentado em 1998 e 2003.";
$lang_var["atlas_titleidhmedu"] = "IDHM Educação";
$lang_var["atlas_metaTitleidhmedu"] = "IDHM Educação";
$lang_var["atlas_metaDescricaoidhmedu"] = "O IDHM Educação é uma composição de indicadores de escolaridade da população adulta e de fluxo escolar da população jovem.";
$lang_var["atlas_titleidhmlong"] = "IDHM Longevidade";
$lang_var["atlas_metaTitleidhmlong"] = "IDHM Longevidade";
$lang_var["atlas_metaDescricaoidhmlong"] = "O IDHM Longevidade – ou IDHM Saúde - considera a esperança de vida ao nascer, ou seja, o número médio de anos que as pessoas dos municípios viveriam a partir do nascimento, mantido os mesmos padrões de mortalidade observados em cada período.";
$lang_var["atlas_titleidhmrend"] = "IDHM Renda";
$lang_var["atlas_metaTitleidhmrend"] = "IDHM Renda";
$lang_var["atlas_metaDescricaoidhmrend"] = "O IDHM Renda considera a renda municipal per capita, ou seja, a renda média mensal dos indivíduos residentes em determinado município, expressa em reais de 1º de agosto de 2010.";
$lang_var["atlas_titleparaque"] = "Para que serve o Atlas";
$lang_var["atlas_metaTitleparaque"] = "Para que serve o Atlas";
$lang_var["atlas_metaDescricaoparaque"] = "O objetivo do Atlas Brasil 2013 é instrumentalizar a sociedade. A democratização de informações no âmbito municipal contribui para o fortalecimento das capacidades locais, o aprimoramento da gestão pública e o empoderamento dos cidadãos brasileiros por meio da ampliação do conhecimento sobre a sua realidade.";
$lang_var["atlas_titleprocesso"] = "Processo de Construção";
$lang_var["atlas_metaTitleprocesso"] = "O processo de construção do Atlas 2013";
$lang_var["atlas_metaDescricaoprocesso"] = "Reunião das equipes do PNUD Brasil, IPEA e FJP para definição de metas e estratégias para o Atlas 2013 ...";
$lang_var["atlas_titlequemfaz"] = "Quem faz";
$lang_var["atlas_metaTitlequemfaz"] = "Quem faz o Atlas Brasil 2013";
$lang_var["atlas_metaDescricaoquemfaz"] = "Programa das Nações Unidas para o Desenvolvimento – PNUD / Instituto de Pesquisa Econômica Aplicada – IPEA / Fundação João Pinheiro - FJP...";
$lang_var["atlas_tutorial"] = 'Tutorial - Atlas Brasil 2013';
$lang_var["atlas_titletutorial"] = 'Tutorial';
$lang_var["atlas_metaTitletutorial"] = 'Tutorial - Atlas Brasil 2013';
$lang_var["atlas_metaDescricaotutorial"] = 'Saiba como usar o Atlas do Desenvolvimento Humano no Brasil 2013.';
$lang_var["atlas_titlefaq"] = 'Perguntas Frequentes';
$lang_var["atlas_metaTitlefaq"] = 'Perguntas Frequentes';
$lang_var["atlas_metaDescricaofaq"] = "O que é Desenvolvimento Humano? Difundido no primeiro Relatório de Desenvolvimento Humano Global do Programa das Nações Unidas para o Desenvolvimento (PNUD), em 1990, pelo economista paquistanês Mahbub ul Haq, o conceito de desenvolvimento humano inspira-se nos trabalhos do prêmio Nobel de Economia Amartya Sen e reforça a ideia de que as pessoas são a verdadeira 'riqueza das nações'. Nessa concepção, desenvolvimento humano é definido como o processo de ampliação das escolhas e liberdades das pessoas para que elas tenham capacidades e oportunidades para serem aquilo que desejam ser. Diferentemente da perspectiva do crescimento econômico, que vê o bem-estar de uma sociedade apenas pelos recursos ou pela renda que ela pode gerar, a abordagem de desenvolvimento humano coloca no centro da discussão as pessoas e suas oportunidades e capacidades.";
$lang_var["atlas_titleiglossario"] = "Glossário";
$lang_var["atlas_metaTitleglossario"] = "Glossário do Atlas do Desenvolvimento Humano no Brasil 2013";
$lang_var["atlas_metaDescricaoglossario"] = "Glossário do Atlas do Desenvolvimento Humano no Brasil 2013";
$lang_var["atlas_titlemetodologia"] = 'Metodologia';
$lang_var["atlas_metaTitlemetodologia"] = 'Metodologia do IDHM 2013';
$lang_var["atlas_metaDescricaometodologia"] = 'Metodologia do IDHM 2013';

$lang_var["footer_novidades"] = "Acompanhe as novidades";
$lang_var["footer_perguntasFrequestes"] = "Perguntas frequentes";
$lang_var["footer_realizacao"] = "Realização";
      
#Árvore
$lang_var["arvore_titulo"] = "Árvore do IDHM";
$lang_var["arvore_subtitulo"] = "Selecione dois municípios ou estados e compare o IDHM através do gráfico abaixo";
$lang_var["arvore_ano1"] ="Ano:";
$lang_var["arvore_ano2"] ="Ano:";
$lang_var["arvore_idhmIdeal"] = "Mostrar IDHM Ideal";
$lang_var["arvore_idhmIdeal2"] = "Mostrar IDHM Ideal";
$lang_var["arvore_idhmComponentes"] = "IDHM e seus componentes";
$lang_var["arvore_idhm"] = "IDHM";
$lang_var["arvore_idhmRenda"] = "IDHM Renda";
$lang_var["arvore_idhmLongevidade"] = "IDHM Longevidade";
$lang_var["arvore_idhmEducacao"] = "IDHM Educação";
$lang_var["arvore_valores"] = "Valores";
$lang_var["arvore_idhmComponentes2"] = "IDHM e seus componentes";
$lang_var["arvore_idhm2"] = "IDHM";
$lang_var["arvore_idhmRenda2"] = "IDHM Renda";
$lang_var["arvore_idhmLongevidade2"] = "IDHM Longevidade";
$lang_var["arvore_idhmEducacao2"] = "IDHM Educação";
$lang_var["arvore_valores2"] = "Valores";
$lang_var["arvore_inspiradoPor"] = "Inspirado por: ";
$lang_var["arvore_btnPrint"] = "Imprimir Árvore IDHM";
$lang_var["arvore_imprimirArvore"] = "Imprimir Árvore";
$lang_var["arvore_toolTipPrintDown"] = "Imprimir Arvore";
$lang_var["arvore_idhm3"] = "IDHM";
$lang_var["arvore_title"] = 'Árvore do IDHM';
$lang_var["arvore_metaTitle"] = 'Árvore do Índice de Desenvolvimento Humano no Brasil 2013';
$lang_var["arvore_metaDescricao"] = 'Exibir indicadores Socieconômicos do Brasil no formato de árvore IDHM';
$lang_var["arvore_renda"] = 'renda';
$lang_var["arvore_edu"] = 'edu';
$lang_var["arvore_longevidadetr"] = 'longevidade';
$lang_var["arvore_idhm4"] = 'IDHM';
$lang_var["arvore_semdados"] = 'Sem Dados';
$lang_var["arvore_tituloprint"] = 'Árvore do IDHM';
$lang_var["arvore_titleprint"] = 'Impressão Árvore do IDHM';

#Gráficos
$lang_var["graficos_titulo"] = 'Gráficos';
$lang_var["graficos_dispersao"] = 'Agregação de 4 Indicadores';
$lang_var["graficos_linhas"] = 'Evolução do Indicadores';
    
$lang_var["download_titulo"] = "Download";
$lang_var["download_dadosBrutos"] = "Dados Brutos";
$lang_var["download_indicadores"] = "Eu quero todos os indicadores e todas as espacialidades disponíveis";
$lang_var["download_buttonBaixe"] = "Baixe Agora";
$lang_var["download_dadosSelecionados"] = "Dados Selecionados";
$lang_var["download_naoSeiIndicadores"] = "Eu ainda não sei as espacialidades e indicadores que quero";
$lang_var["download_cliqueConsulta"] = "Clique em \"Consulta\" faça sua seleção e baixe o que quiser";
$lang_var["download_buttonConsulta"] = "Consulta";
$lang_var["download_title"] = "Download";
$lang_var["download_metaTitle"] = "Download dos dados do Atlas do Desenvolvimento Humano no Brasil 2013";
$lang_var["download_metaDescricao"] = "Faça download de todos  os indicadores e espacialidades disponíveis e/ou selecione as dados desejados.";

$lang_var['notas_title'] = "Notas";
$lang_var['notas_texto'] = "As seguintes variáveis do Atlas Brasil 2013 estão com dados preliminares para determinados anos:";
$lang_var['notas_sigla'] = "SIGLA";
$lang_var['notas_nomecurto'] = "NOME CURTO";
$lang_var['notas_ano'] = "ANO";
$lang_var['notas_analf11a14'] = "Taxa de analfabetismo - 11 a 14 anos";
$lang_var['notas_analf15a17'] = "Taxa de analfabetismo - 15 a 17 anos";
$lang_var['notas_analf15m'] = "Taxa de analfabetismo - 15 anos ou mais";
$lang_var['notas_analf18a24'] = "Taxa de analfabetismo - 18 a 24 anos";
$lang_var['notas_analf18m'] = "Taxa de analfabetismo - 18 anos ou mais";
$lang_var['notas_analf25a29'] = "Taxa de analfabetismo - 25 a 29 anos";
$lang_var['notas_analf25m'] = "Taxa de analfabetismo - 25 anos ou mais";
$lang_var['notas_agua'] = "% da população em domicílios com água encanada";
$lang_var['notas_renocup'] = "Rendimento médio dos ocupados - 18 anos ou mais";
$lang_var['notas_crifundinTodos'] = "% de crianças em domicílios em que ninguém tem fundamental completo";
$lang_var['notas_peso1114'] = "População de 11 a 14 anos";
$lang_var['notas_peso1113'] = "População de 11 a 13 anos";
$lang_var['notas_peso1214'] = "População de 12 a 14 anos";
$lang_var['notas_peso13'] = "População de 1 a 3 anos";
$lang_var['notas_peso1517'] = "População de 15 a 17 anos";
$lang_var['notas_peso1524'] = "População de 15 a 24 anos";
$lang_var['notas_peso1618'] = "População de 16 a 18 anos";
$lang_var['notas_peso18'] = "População de 18 anos ou mais";
$lang_var['notas_peso1820'] = "População de 18 a 20 anos";
$lang_var['notas_peso1824'] = "População de 18 a 24 anos";
$lang_var['notas_peso1921'] = "População de 19 a 21 anos";
$lang_var['notas_peso4'] = "População de 4 anos";
$lang_var['notas_peso5'] = "População de 5 anos";
$lang_var['notas_peso6'] = "População de 6 anos";
$lang_var['notas_peso610'] = "População de 6 a 10 anos";
$lang_var['notas_peso617'] = "População de 6 a 17 anos";
$lang_var['notas_pesom1517'] = "Mulheres de 15 a 17 anos";
$lang_var['notas_199120001'] = "1991 e 2000";
$lang_var['notas_199120002'] = "1991 e 2000";
$lang_var['notas_199120003'] = "1991 e 2000";
$lang_var['notas_199120004'] = "1991 e 2000";
$lang_var['notas_199120005'] = "1991 e 2000";
$lang_var['notas_199120006'] = "1991 e 2000";
$lang_var['notas_199120007'] = "1991 e 2000";

    
$lang_var["mapa_espacialidade"] ="espacialidade";
$lang_var["mapa_indicadores"] ="indicadores";
$lang_var["mapa_ano"] ="ano";
$lang_var["mapa_zoomin"] ="Mais zoom";
$lang_var["mapa_zoomout"] ="Menos zoom";
$lang_var["mapa_brasil"] ="Brasil completo";
$lang_var["mapa_regiao"] = "Selecionar região";
$lang_var["mapa_quintil"] ="Quintil";
$lang_var["mapa_qtool"] ="Gerar quintil a partir da seleção atual";
$lang_var["mapa_imprimir"] ="Imprimir mapa";
$lang_var["mapa_legenda"] ="Mostrar legenda";
$lang_var["mapa_miniperfil"] ="Mostrar miniperfil";
$lang_var["mapa_ver"] ="Ver no mapa";
$lang_var["mapa_voltar"] ="Voltar";
$lang_var["mapa_areas_tematicas"] ="Áreas temáticas";
$lang_var["mapa_estados"] ="Estados";
$lang_var["mapa_municipios"] ="Municípios";
$lang_var["mapa_voltar_msg"] ="Retornar a exibição padrão";
$lang_var["mapa_leg"] ="Legenda";
$lang_var["mapa_idh_img"] ="img/map/idhm.png";
$lang_var["mapa_municipio"] = "Município";
$lang_var["mapa_estado"] = "Estado";
$lang_var["mapa_exibir_perfil"] = "Exibir perfil";
$lang_var["mapa_title"] = "Perfil";
$lang_var["mapa_title_mun"] = "Perfil do município de ";
$lang_var["mapa_metaTitle"] = "Perfil Socieconômico dos Municípios do Brasil";
$lang_var["mapa_metaDescricao"] = "Visualize o perfil socieconômico das cidades brasileiras";


    
$lang_var["seletor_espacialidade"] ="Espacialidade";
$lang_var["seletor_estado"] ="Estado";
$lang_var["seletor_selecionados"] ="Selecionados";
$lang_var["seletor_municipios"] ="Municípios";
$lang_var["seletor_todos"] ="Marcar todos";
$lang_var["seletor_areas"] ="Áreas";
$lang_var["seletor_estadual"] ="Estadual";
$lang_var["seletor_municipal"] ="Municipal";
$lang_var["seletor_tematico"] ="Áreas temáticas";
$lang_var["seletor_dimensao"] ="Dimensão";
$lang_var["seletor_tema"] ="Temas";
$lang_var["seletor_indicador"] ="Indicadores";
$lang_var["seletor_lim_tab"] = "Seleção atual: Indicadores ($1), Lugares ($2), Células($3). A tabela será disponibilizada para download.";
$lang_var["seletor_lim_down"] = "Atenção: sua consulta superou o limite de ($1) células na tabela. <br/> Acesse \"Download\" e baixe todos os dados do Atlas Brasil 2013.";
$lang_var["seletor_todos_estados"] ="Todos os Estados";
$lang_var["seletor_selec_todos"] ="Selecionar todos";


$lang_var["rankin_title_01"] ="Todo o Brasil";
$lang_var["rankin_title_02"] ="Todos os Estados";
$lang_var["rankin_ranking"] ="Ranking";
$lang_var["rankin_municipal"] ="Municipal";
$lang_var["rankin_Estadual"] ="Estadual";
$lang_var["rankin_Ano"] ="ANO";
$lang_var["rankin_estado"] ="Estado";
$lang_var["rankin_todos"] ="Todos";
$lang_var["rankin_order_by"] ="Ordenado pelo";
$lang_var["rankin_faixas"] ="Faixas de desenvolvimento humano";
$lang_var["rankin_fm_alto"] ="Muito Alto";
$lang_var["rankin_alto"] ="Alto";
$lang_var["rankin_medio"] ="Médio";
$lang_var["rankin_baixo"] ="Baixo";
$lang_var["rankin_m_baixo"] ="Muito Baixo";
$lang_var["rankin_Lugar"] ="Lugares";
$lang_var["rankin_posicao"] ="Posição";
$lang_var["rankin_idhm"] ="IDHM";
$lang_var["rankin_renda"] ="IDHM Renda";
$lang_var["rankin_edu"] ="IDHM Educação";
$lang_var["rankin_Long"] ="IDHM Longevidade";
$lang_var["rankin_renda2"] ="IDHM<br />Renda";
$lang_var["rankin_exibir_all"] ="Exibir todos os resultados";
$lang_var["rankin_r_topo"] ="Retornar ao topo";
$lang_var["rankin_title"] = "Ranking";
$lang_var["rankin_metaTitle"] = "Ranking do IDH dos Municípios e Estados do Brasil";
$lang_var["rankin_metaDescricao"] = "Visualize a posição das cidades e estados brasileiros no ranking do Índice de Desenvolvimento Humano Municipal.";

$lang_var["selecionar"] ="Selecionar";
$lang_var["marcar_todos"] ="Marcar todos";
$lang_var["desmarcar_todos"] ="Desmarcar todos";
$lang_var["limpar_lugares"] ="Limpar lugares";
$lang_var["limpar_indicadores"] ="Limpar indicadores";
$lang_var["tabela_ver"] ="Ver na tabela";
$lang_var["download_text"] = "Download da lista em formato csv (compatível com o Microsoft Excel e outras planilhas eletrônicas).";
$lang_var["limpar_selecionados"] ="Limpar selecionados";
$lang_var["carregando"] = "Carregando dados..";
$lang_var["preenche"] = "Preenchendo tabela...";
$lang_var["limpa"] = "Limpando tabela...";

$lang_var["caixa_digite"] = "Digite o nome de algum Município";
$lang_var["caixa_nenhum"] = "Nenhum registro encontrado";
$lang_var["caixa_perfil"] = "";

$lang_var["caixa_est_mun"] = "Digite o nome de algum Município ou Estado";

$lang_var["meta_title"] = "Consulta do Atlas de Desenvolvimento Humano 2013";
$lang_var["meta_description"] = "Realize consultas sobre os indicadores socieconômicos brasileiros da localidade desejada, e visualize-os em tabelas e mapas";

$lang_var["msg_down01"] = "Antes de realizar o download selecione pelo menos uma espacialidade e um indicador.";
$lang_var["msg_alerta_download"] = "Alguns dados são preliminares ou não estão disponíveis para o ano de 1991. Consulte os detalhes <a href=".$path_dir.'pt/notas/'." target=\'_blank\'>aqui</a>.";
$lang_var["col_download_csv"] = "Lugar"; 
$lang_var["cols_ranking_pos"] = "Posição"; 
$lang_var["cols_ranking_na"] = "Nome";


?>