<div id="metodologia" style="width: 900px; height: 1993px;">
    <div id="img_vida"><img src="./img/o_atlas/dimensao_padrao_de_vida.jpg" ></div>
    <div id="dim_saud" >
        <h1 style="color: #BDBDBD;">Dimension: Income</h1>
        <div class="block-01-div-subtitle" style="margin-top: -17px; font-size: 23pt; margin-bottom: -13px;">Standard of living</div>
        <p>In MHDI, this dimension is measured by the monthly income <i>per capita</i>.</p>
    </div>
    <div class="clear"></div>
    <div id="dim_saud_direita" style='height: 1575px;'>
        <img src="./img/o_atlas/o_que_componhe.jpg" id="dim_saud_images">
        <div id="text_met">
	<span><b>What does the MHDI Income consist of?</b></span><br />
	The MHDI Income examines the municipal income <i>per capita</i>; in other words, the monthly income of the residents in a certain municipality, in Brazilian Reals (R$.) from 1st of August 2010.
        </div>
        <div class="clear"></div>
        <img src="./img/o_atlas/o_que_merece.jpg" id="dim_saud_images">
        <div id="text_met">
	<span><b>What does the indicator measure?</b></span><br />
	Income <i>per capita</i> measures the average capacity of procuring goods and services by the inhabitants of a municipality.
        </div>
        <div class="clear"></div>
        <img src="./img/o_atlas/porque_esse_indicador.jpg" id="dim_saud_images">
        <div id="text_met">
	<span><b>Why this indicator?</b></span><br />
	This indicator shows the ability of the inhabitants in a municipality to ensure a decent standard of living to ensure their basic needs, such as water, food and shelter.
        </div>
        <div class="clear"></div>
        <img src="./img/o_atlas/como_e_calculado.jpg" id="dim_saud_images">
        <div id="text_met">
	<span><b>How is the indicator calculated?</b></span><br />
	The values are obtained from the questionnaire responses of a sample of the Demographic Census. The indicator presents the ratio of the sum of all income that all of the individuals of the municipality received in the month prior to the date of the Census, and the total number of these individuals. The income figures calculated from the Censuses of 1991 and 2000, in cruzeiros of 1st September 1991 and in reais, of 1st August 2000, were converted into reais from August 1, 2010 (the reference date of the 2010 Census.) For this reason, we used the series from the National Index Consumer Price Index (INPC) from IBGE (converted into a series centered on the first day of each month) but, considering that this series underestimated inflation by 22.25% in July/1994 from that date forward, a correcting factor of 1.2225 was applied.
        </div>
        <div class="clear"></div>
        <img src="./img/o_atlas/limitacoe.jpg" id="dim_saud_images">
        <div id="text_met">
	<span><b>Limitations</b></span><br />
	The major limitation of this indicator is that it does not examine income inequality among the inhabitants of the municipality. Hence, a municipality may have a high income per capita, but, at the same time, a large portion of its population may be living in poverty.
        </div>
        <div class="clear"></div>
        <img src="./img/o_atlas/peso_variaveis.jpg" id="dim_saud_images">
        <div id="text_met">
	<span><b>The weights of the variables</b></span><br />
            In the index there is only one variable with a weight of 1.
        </div>
        <div class="clear"></div>
        <img src="./img/o_atlas/comparacoes_ajustes.jpg" id="dim_saud_images">
        <div id="text_met">
	<span><b>Comparison and adjustments within the global HDI</b></span><br />
	The Gross Domestic Product (GDP) is the value added by the production of all goods and services over a year within a given boundary. The GDP <i>per capita</i> is the division of this value by the population of a country that the UNDP has used for the calculation of HDI of countries and states worldwide until 2010. In 2010, this indicator was replaced by the GNI (Gross National Income) <i>per capita</i>. 
            <p>The use of GDP <i>per capita</i> becomes inadequate when assessing the income of the inhabitants of a municipality, because not all of the income generated by production within the municipal area is appropriated for the resident population (and vice versa). On the other hand, there are no municipal statistics for GNI <i>per capita</i>. The alternative used calculates the municipal income <i>per capita</i> obtained from the Demographic Census.</p>
        </div>
        <div class="clear"></div>
        <img src="./img/o_atlas/fonte.jpg" id="dim_saud_images">
        <div id="text_met">
	<span><b>The source of information</b></span><br />
	The Demographic Censuses 1991, 2000 and 2010, conducted by IBGE.
        </div>
        <div class="clear"></div>
        <img src="./img/o_atlas/suporte_analise.jpg" id="dim_saud_images">
        <div id="text_met">
	<span><b>Support indicators in analysing MHDI Income</b></span><br />
	In addition to municipal income per capita, Atlas Brazil 2013 presents various supportive indicators (such as income <i>per capita</i> by population quintiles, the ratio between the income <i>per capita</i> of the richest 10% and 20% and the income <i>per capita</i> of the poorest 40% of the population, as well as the Gini and Theil Indices) that examine income-related inequalities. Poverty is also reviewed by three poverty lines - R$ 70, R$ 140 and R$ 255. To calculate these indicators, Atlas 2013 has adopted the household income <i>per capita</i> (assuming that all people in the same household have the same income).
        </div>
        <div class="clear"></div>
        <img src="./img/o_atlas/calculo_longevidade.jpg" id="dim_saud_images">
        <div id="text_met">
	<span><b>How to calculate MHDI Income</b></span><br />
	The formula applied to calculate MHDI Income is:<br />
            MHDI-I = [ln (municipal income <i>per capita</i>) - ln (minimum value of reference)] / [ln (maximum value of reference) - ln (minimum value of reference)]<br /><br />
            <p>This logarithm applied in the formula brings the maximum values of income <i>per capita</i> closer to the minimum values – and therefore, it reduces the existing income inequality. However, this procedure assumes that, as the income <i>per capita</i> increases, the return of this increased income, in terms of human development, decreases.</p>
            <p>Maximum amount: R$ 4,033.00 - is equivalent to the amount of the lowest income <i>per capita</i> among the richest 10% of residents at FUs (Federative Units) with the highest average income in the country during the analysed period: the Federal District.</p>
            <p>Minimum amount: R$ 8.00 - is equivalent to, approximately, US$ 100 PPS (Purchasing Power Standards), which is the constraint used in calculating the global HDI. </p>
            <p>For a municipality with a municipal income <i>per capita</i> of R$ 827.35, the calculation would be as follows: <br /> 
            MHDI-I = (ln 827.35 - 8.00 ln) / (ln 4033.00 - 8.00 ln) => MHDI-I = 0.745.</p>
        </div>
    </div>
</div>

<?php
    $title2 = $lang_mng->getString("atlas_titleidhmrend");
    $meta_title2 = $lang_mng->getString("atlas_metaTitleidhmrend");
    $meta_description2 = $lang_mng->getString("atlas_metaDescricaoidhmrend");
?>    